name: quill_html_editor_v3
description: Yet, another fork of the quill_html_editor package fixing some issues that no one else wants to fix.

version: 2.2.12
homepage: https://github.com/zviri/quill_html_editor
repository: https://github.com/zviri/quill_html_editor
maintainer: Zviri

environment:
  sdk: '>=2.18.1 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  ##### For image picker widget
  file_picker: ^10.1.9
  ##### For webveiwx widget
  http: ^1.2.1
  path: ^1.9.0
  pointer_interceptor: ^0.10.1
  uuid: ^4.3.3
  webview_flutter: ^4.4.4
  webview_flutter_android: ^4.7.0
  webview_flutter_platform_interface: ^2.9.0
  webview_flutter_wkwebview: ^3.10.2
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_lints: ^4.0.0 

flutter:
  assets:
      - packages/quill_html_editor_v3/assets/camera_roll_icon.png
      - packages/quill_html_editor_v3/assets/h1_dark.png
      - packages/quill_html_editor_v3/assets/h2_dark.png
      - packages/quill_html_editor_v3/assets/edit_table.png
      - packages/quill_html_editor_v3/assets/insert_table.png
      - packages/quill_html_editor_v3/assets/delete_column.png
      - packages/quill_html_editor_v3/assets/delete_row.png
      - packages/quill_html_editor_v3/assets/delete_table.png
      - packages/quill_html_editor_v3/assets/insert_column_left.png
      - packages/quill_html_editor_v3/assets/insert_row_above.png
      - packages/quill_html_editor_v3/assets/insert_row_below.png
      - packages/quill_html_editor_v3/assets/insert_column_right.png
      - packages/quill_html_editor_v3/assets/scripts/quill_2.0.0_4_min.js
